feat: add test on docker-compose.test.yml

diff --git a/py2/ubuntu/16.04/docker-compose.test.yml b/py2/ubuntu/16.04/docker-compose.test.yml
--- a/py2/ubuntu/16.04/docker-compose.test.yml
+++ b/py2/ubuntu/16.04/docker-compose.test.yml
@@ -1,6 +1,12 @@
 sut:
   build: .
   command: >
-      sh -c "id -u imio | grep -q '913' &&
-             date | grep -q 'CEST'"
-
+      sh -c "
+        if id -u imio | grep -q '913' && date | grep -q 'CEST'; then
+          echo \"Tests passed!\"
+          exit 0
+        else
+          echo \"Tests failed!\"
+          exit 1
+        fi
+      "
